#!/usr/local/bin/ruby

require 'rest_client'
require 'json'

stdin = STDIN.read
json = JSON.parse(stdin)
version_ref = json["version"]["ref"]

STDOUT.write "{ \"version\": { \"ref\": \"#{version_ref}\" } }"
